# backend:
#   name: git-gateway
#   branch: master

local_backend: true
backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1
  branch: master # optional, defaults to master

media_folder: static/img
public_folder: /img

collections:
  - name: "programs"
    label: "Programs"
    folder: "src/pages/programs"
    identifier_field: name
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "program-page",
        }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Background Image", name: "backgroundImage", widget: "image" }
      - label: "Important Faq Section"
        name: "importantFaqSection"
        widget: object
        # default: ""
        required: false
        fields:
          - {
              label: "Description",
              name: "description",
              widget: "markdown",
              # default: "",
              required: false,
            }
          - label: "Questions"
            name: questions
            widget: list
            # default: ""
            required: false
            fields:
              - label: "Question"
                name: question
                widget: string
                # default: ""
                required: false
              - label: "Answer"
                name: answer
                widget: markdown
                # default: ""
                required: false
      - label: "Regular FAQ"
        name: faqSection
        widget: object
        # default: ""
        required: false
        fields:
          - label: "Title"
            name: title
            widget: string
            # default: ""
            required: false
          - label: "Subtitle"
            name: subtitle
            widget: string
            # default: ""
            required: false
          - label: "Body"
            name: body
            widget: markdown
            # default: ""
            required: false
          - label: "Questions"
            name: questions
            widget: list
            fields:
              - label: "Question"
                name: question
                widget: string
                # default: ""
                required: false
              - label: "Answer"
                name: answer
                widget: markdown
                # default: ""
                required: false
      - label: "Learn more"
        name: learnMoreSection
        widget: object
        fields:
          - label: "Title"
            name: title
            widget: string
            # default: ""
            required: false
          - label: "Subtitle"
            name: subtitle
            widget: string
            # default: ""
            required: false
          - label: "Body"
            name: body
            widget: markdown
            # default: ""
            required: false
          - label: "Questions"
            name: questions
            widget: list
            fields:
              - label: "Question"
                name: question
                widget: string
                # default: ""
                required: false
              - label: "Answer"
                name: answer
                widget: string
                # default: ""
                required: false
      - label: "Contact Us Section"
        name: contactUsSection
        widget: object
        fields:
          - label: "Title"
            name: title
            widget: string
            # default: ""
            required: false
          - label: "Subtitle"
            name: subtitle
            widget: string
            # default: ""
            required: false
          - label: "Body"
            name: body
            widget: markdown
            # default: ""
            required: false
      - label: "Custom CSS"
        name: customStyle
        widget: markdown
        # default: ""
        required: false

  - name: "blog"
    label: "Blog"
    folder: "src/pages/archive"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
  - name: "configurations"
    label: "Site configurations"
    files:
      - file: "src/pages/config/index.md"
        label: "Site Configurations"
        name: "site-config"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "site-config",
            }
          - { label: "Slogan", name: "slogan", widget: "string" }
          - label: "Social Media"
            name: "socialMedia"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "URL"
                name: "url"
                widget: "string"
              - label: "Icon"
                name: "icon"
                hint: "Use font awesome icons eg:. fa fa-linkedin-square"
                default: "fa fa-linkedin-square"
          - label: "Menus"
            name: "menus"
            widget: "object"
            fields:
              - label: "Header Navigation"
                name: "header"
                widget: "code"
              - label: "Footer Navigation"
                name: "footer"
                widget: "code"

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - label: "Presentation Section"
            name: "presentationSection"
            widget: object
            fields:
              - { label: "Section Title", name: "title", widget: "string" }
              - {
                  label: "Section Subtitle",
                  name: "subtitle",
                  widget: "string",
                }
              # default: "",
              - label: "Transformations"
                name: "transformation"
                widget: "list"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Body", name: body, widget: markdown }
              - label: "CTA Button"
                name: "ctaButton"
                widget: object
                fields:
                  - { label: "Label", name: label, widget: string }
                  - { label: "Sublabel", name: sublabel, widget: string }
                  # default: "",
                  - { label: "URL", name: url, widget: string }
          - label: "Why Care Section"
            name: "whyCareSection"
            widget: object
            fields:
              - { label: "Section Title", name: "title", widget: "string" }
              - {
                  label: "Section Subtitle",
                  name: "subtitle",
                  widget: "string",
                  required: false,
                }
              - { label: "Body", name: body, widget: markdown, required: false }
              - label: "CTA Button"
                name: "ctaButton"
                widget: object
                fields:
                  - { label: "Label", name: label, widget: string }
                  - {
                      label: "Sublabel",
                      name: sublabel,
                      widget: string,
                      required: false,
                    }
                  - { label: "URL", name: url, widget: string }
          - label: "Why You Crucial Section"
            name: "whyYouCrucialSection"
            widget: object
            fields:
              - { label: "Section Title", name: "title", widget: "string" }
              - {
                  label: "Section Subtitle",
                  name: "subtitle",
                  widget: "string",
                  required: false,
                }
              - { label: "Body", name: body, widget: markdown, required: false }
              - label: "CTA Button"
                name: "ctaButton"
                required: false
                widget: object
                fields:
                  - { label: "Label", name: label, widget: string }
                  - {
                      label: "Sublabel",
                      name: sublabel,
                      widget: string,
                      required: false,
                    }
                  - { label: "URL", name: url, widget: string }
          - label: "Solutions"
            name: "solutionsSection"
            widget: object
            fields:
              - { label: "Section Title", name: "title", widget: "string" }
              - {
                  label: "Section Subtitle",
                  name: "subtitle",
                  widget: "string",
                  required: false,
                }
              - { label: "Body", name: body, widget: markdown, required: false }
              - label: "Programs"
                name: programs
                widget: list
                fields:
                  - label: "Name"
                    name: name
                    widget: string
                  - label: "Description"
                    name: description
                    widget: markdown

              - label: "CTA Button"
                name: "ctaButton"
                widget: object
                fields:
                  - { label: "Label", name: label, widget: string }
                  - {
                      label: "Sublabel",
                      name: sublabel,
                      widget: string,
                      required: false,
                    }
                  - { label: "URL", name: url, widget: string }

      - file: "src/pages/about-us/index.md"
        label: "About Us"
        name: "about-us"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-us-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Background Image",
              name: "backgroundImage",
              widget: "image",
            }
          - { label: "Description", name: "description", widget: "markdown" }
          - label: "Overview Section"
            name: overviewSection
            widget: object
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
              - { label: "Body", name: "body", widget: "markdown" }
              - label: "Things we are doing"
                name: things
                widget: "list"
                fields:
                  - label: "Title"
                    name: title
                    widget: string
                  - label: "Description"
                    name: description
                    widget: markdown
          - label: "Contact Us Section"
            name: contactUsSection
            widget: object
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
              - { label: "Body", name: "body", widget: "markdown" }
          - label: "Support Us Section"
            name: supportUsSection
            widget: object
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
              - { label: "Body", name: "body", widget: "markdown" }
              - label: "CTA Button"
                name: "ctaButton"
                widget: object
                fields:
                  - { label: "Label", name: label, widget: string }
                  - {
                      label: "Sublabel",
                      name: sublabel,
                      widget: string,
                      required: false,
                    }
                  - { label: "URL", name: url, widget: string }
